### PR TITLE
Fix #165

### LINKED ISSUE #165: integrity_SUITE's async_insertion_roundtrip seems to depend on the Cassandra partitioner
`async_insertion_roundtrip` does this, per my understanding:
- assumes there's already a row in `test_keyspace_2.entries1`:
  ```
   id      | age | email
  ---------+-----+---------------------
     hello |  18 | mathieu@damours.org
  ```
- inserts a new one:
  ```
   id      | age | email
  ---------+-----+---------------------
   1234123 |  45 |    yvon@damours.org
  ```
- fetches all rows from `test_keyspace_2.entries1`
- gets the second one using `cqerl:next/1`
- matches it against the `1234123`/`45`/`yvon@damours.org` triplet, the exact data this function has inserted in step 2

The problem is that the order of these rows depends on the partitioner the cluster has been configured with. I'm using `ByteOrderedPartitioner`, which isn't ideal, I know, but it seems to be causing a problem with this unit test

### PR DESCRIPTION
**Pull request by portasynthinca3**

### CODE REVIEW

**Comment by portasynthinca3** [comment]
Okay, maybe it's not #165 _only_ :sweat_smile:

**Comment by portasynthinca3** [comment]
`make test` succeeds

**Comment by matehat** [comment]
Thanks! 

I wonder why CircleCI doesn't kick in... 🤨

**Comment by matehat** [comment]
Are you sure you're up to date with master? c7777c6 doesn't seem to fit with [what's in master](https://github.com/cqerl/cqerl/blob/3544d5a5f3b9bebeae94fa34c8625cc6e4ba6677/src/cqerl_client.erl#L736-L747)

**Comment by portasynthinca3** [comment]
Yeah, the last one fixed that

**Pull request merged**
