### PR TITLE
Support Unicode for text data types

### PR DESCRIPTION
**Pull request by portasynthinca3**
I ran into a problem in one of my projects that requires me to handle Unicode strings correctly. The `list_to_binary/1` BIF CQErl is currently using throws a `badarg` on any strings containing non-ASCII characters. Using `characters_to_binary/1` and `characters_to_list/1` from the `unicode` module is more appropriate when the Cassandra datatype is right.

### CODE REVIEW

**Comment by matehat** [comment]
@portasynthinca3 thank you for this!

Have you had the chance to run the test suite on it?

**Comment by portasynthinca3** [comment]
Sorry to tell you, but it seems to fail -
```
{{badmatch,"hello"},
 [{integrity_SUITE,simple_insertion_roundtrip,1,
                   [{file,"/home/portasynthinca3/cqerl/test/integrity_SUITE.erl"},
                    {line,268}]},
  {test_server,ts_tc,3,[{file,"test_server.erl"},{line,1748}]},
  {test_server,run_test_case_eval1,6,[{file,"test_server.erl"},{line,1263}]},
  {test_server,run_test_case_eval,9,[{file,"test_server.erl"},{line,1195}]}]}
```
In this function:
```erl
simple_insertion_roundtrip(Config) ->
    Client = get_client(Config),
    Q = <<"INSERT INTO entries1(id, age, email) VALUES (?, ?, ?)">>,
    {ok, void} = cqerl:run_query(Client, #cql_query{statement=Q, values=[
        {id, "hello"},
        {age, 18},
        {email, <<"mathieu@damours.org">>}
    ]}),
    {ok, Result=#cql_result{}} = cqerl:run_query(Client, #cql_query{statement = <<"SELECT * FROM entries1;">>}),
    Row = cqerl:head(Result),
    <<"hello">> = proplists:get_value(id, Row), % <--- here
                                                % the modified "decode" evaluates to a list, not a binary
    18 = proplists:get_value(age, Row),
    <<"mathieu@damours.org">> = proplists:get_value(email, Row),
    Result.
```

**Comment by portasynthinca3** [comment]
`characters_to_binary/`` instead of `characters_to_list/1` might actually be better

**Comment by matehat** [comment]
Thanks, I went ahead and did that, along with other fixes and published the next stable version: 2.1.0. Thanks a lot again for your contribution!

**Comment by portasynthinca3** [comment]
No problem, thank you for writing the original driver!

**Pull request merged**
